const axios = require('axios');

/**
 * Vodacom DRC M-Pesa Service
 * Handles C2B (deposit) and B2C (withdrawal/send-money) flows
 * for Vodacom Democratic Republic of Congo.
 *
 * Country code : +243
 * Sandbox base : https://openapi.m-pesa.com/sandbox/ipg/v2/vodacomDRC/
 *
 * When MPESA_SIMULATION=true the class returns realistic fake responses
 * so the full money-flow can be exercised without live credentials.
 */
class VodacomMpesaService {
    constructor() {
        this.apiKey                = process.env.VODACOM_MPESA_API_KEY;
        this.publicKey             = process.env.VODACOM_MPESA_PUBLIC_KEY;
        this.serviceProviderCode   = process.env.VODACOM_MPESA_SERVICE_PROVIDER_CODE || 'SP001';
        this.initiatorIdentifier   = process.env.VODACOM_MPESA_INITIATOR_IDENTIFIER;
        this.securityCredential    = process.env.VODACOM_MPESA_SECURITY_CREDENTIAL;
        this.environment           = process.env.MPESA_ENVIRONMENT || 'sandbox';
        this.callbackUrl           = process.env.VODACOM_CALLBACK_URL;
        this.simulationMode        = process.env.MPESA_SIMULATION === 'true';

        // Vodacom DRC sandbox base URL
        this.baseUrl = 'https://openapi.m-pesa.com';
        this.apiPath = `/sandbox/ipg/v2/vodacomDRC`;

        // Session cache
        this.sessionToken  = null;
        this.sessionExpiry = null;
        this.SESSION_TTL   = 25 * 60 * 1000; // 25 min (token valid 30 min)
    }

    // ─────────────────────────────────────────────
    // INTERNAL HELPERS
    // ─────────────────────────────────────────────

    /**
     * Normalise a phone number to the DRC E.164 format 243XXXXXXXXX
     */
    _normalisePhone(raw) {
        // Strip everything except digits
        let digits = String(raw).replace(/\D/g, '');

        // Remove leading + if present (already stripped above)
        // Handle 00243..., +243..., 243..., 0...
        if (digits.startsWith('00243')) digits = digits.slice(5);
        else if (digits.startsWith('243'))  digits = digits.slice(3);
        else if (digits.startsWith('0'))    digits = digits.slice(1);

        return `243${digits}`;
    }

    _generateSimRef(prefix = 'SIM') {
        return `${prefix}${Date.now()}${Math.random().toString(36).substr(2, 6).toUpperCase()}`;
    }

    // ─────────────────────────────────────────────
    // SESSION TOKEN
    // ─────────────────────────────────────────────

    async getSessionToken() {
        if (this.simulationMode) {
            return 'SIM_SESSION_TOKEN';
        }

        // Return cached token if still valid
        if (this.sessionToken && this.sessionExpiry && Date.now() < this.sessionExpiry) {
            return this.sessionToken;
        }

        console.log('🔐 Fetching new Vodacom DRC M-Pesa session token…');

        const response = await axios.get(
            `${this.baseUrl}${this.apiPath}/getSession/`,
            {
                headers: {
                    Authorization: `Bearer ${this.apiKey}`,
                    'Content-Type': 'application/json'
                }
            }
        );

        if (!response.data?.output_SessionID) {
            throw new Error('Vodacom did not return a session token');
        }

        this.sessionToken  = response.data.output_SessionID;
        this.sessionExpiry = Date.now() + this.SESSION_TTL;
        console.log('✅ Session token obtained');
        return this.sessionToken;
    }

    // ─────────────────────────────────────────────
    // C2B  –  Customer → Business  (DEPOSIT)
    // ─────────────────────────────────────────────

    /**
     * @param {string} phoneNumber   - Customer's DRC mobile number
     * @param {number} amount        - Amount to collect
     * @param {string} currency      - 'USD' or 'KES'
     * @param {string} transactionRef - Unique reference generated by our system
     * @param {string} description   - Short description shown to customer
     */
    async initiateC2BPayment(phoneNumber, amount, currency, transactionRef, description) {
        if (this.simulationMode) {
            return this._simulateC2B(phoneNumber, amount, currency, transactionRef);
        }

        try {
            console.log(`📱 C2B deposit: ${amount} ${currency} from ${phoneNumber}`);

            const sessionToken = await this.getSessionToken();
            const msisdn       = this._normalisePhone(phoneNumber);

            const payload = {
                input_ServiceProviderCode:  this.serviceProviderCode,
                input_CustomerMSISDN:       msisdn,
                input_Amount:               parseFloat(amount),
                input_ThirdPartyReference:  transactionRef,
                input_TransactionReference: transactionRef,
                input_PurchasedItemsDesc:   description || `Deposit ${amount} ${currency}`
            };

            console.log('📤 C2B payload:', JSON.stringify(payload, null, 2));

            const response = await axios.post(
                `${this.baseUrl}${this.apiPath}/c2bPayment/singleStage/`,
                payload,
                {
                    headers: {
                        Authorization: `Bearer ${sessionToken}`,
                        'Content-Type': 'application/json'
                    }
                }
            );

            console.log('📥 C2B response:', JSON.stringify(response.data, null, 2));

            if (response.data?.output_ResponseCode === 'INS-0') {
                return {
                    success:             true,
                    transactionID:       response.data.output_TransactionID,
                    conversationID:      response.data.output_ConversationID,
                    thirdPartyReference: transactionRef,
                    responseDescription: response.data.output_ResponseDesc || 'Payment initiated'
                };
            }

            return {
                success:             false,
                responseCode:        response.data?.output_ResponseCode || 'UNKNOWN',
                responseDescription: response.data?.output_ResponseDesc  || 'Payment failed'
            };

        } catch (error) {
            console.error('❌ C2B error:', error.response?.data || error.message);
            return {
                success:             false,
                responseCode:        'API_ERROR',
                responseDescription: error.response?.data?.output_ResponseDesc || error.message
            };
        }
    }

    // ─────────────────────────────────────────────
    // B2C  –  Business → Customer  (WITHDRAWAL / SEND MONEY)
    // ─────────────────────────────────────────────

    /**
     * @param {string} phoneNumber   - Recipient's DRC mobile number
     * @param {number} amount        - Amount to send
     * @param {string} currency      - 'USD' or 'KES'
     * @param {string} transactionRef - Unique reference generated by our system
     * @param {string} description   - Short description
     */
    async initiateB2CPayment(phoneNumber, amount, currency, transactionRef, description) {
        if (this.simulationMode) {
            return this._simulateB2C(phoneNumber, amount, currency, transactionRef);
        }

        try {
            console.log(`💸 B2C payment: ${amount} ${currency} to ${phoneNumber}`);

            const sessionToken = await this.getSessionToken();
            const msisdn       = this._normalisePhone(phoneNumber);

            const payload = {
                input_ServiceProviderCode:  this.serviceProviderCode,
                input_CustomerMSISDN:       msisdn,
                input_Amount:               parseFloat(amount),
                input_ThirdPartyReference:  transactionRef,
                input_TransactionReference: transactionRef,
                input_PaymentItemsDesc:     description || `Payment ${amount} ${currency}`
            };

            console.log('📤 B2C payload:', JSON.stringify(payload, null, 2));

            const response = await axios.post(
                `${this.baseUrl}${this.apiPath}/b2cPayment/`,
                payload,
                {
                    headers: {
                        Authorization: `Bearer ${sessionToken}`,
                        'Content-Type': 'application/json'
                    }
                }
            );

            console.log('📥 B2C response:', JSON.stringify(response.data, null, 2));

            if (response.data?.output_ResponseCode === 'INS-0') {
                return {
                    success:             true,
                    transactionID:       response.data.output_TransactionID,
                    conversationID:      response.data.output_ConversationID,
                    thirdPartyReference: transactionRef,
                    responseDescription: response.data.output_ResponseDesc || 'Payment sent'
                };
            }

            return {
                success:             false,
                responseCode:        response.data?.output_ResponseCode || 'UNKNOWN',
                responseDescription: response.data?.output_ResponseDesc  || 'Payment failed'
            };

        } catch (error) {
            console.error('❌ B2C error:', error.response?.data || error.message);
            return {
                success:             false,
                responseCode:        'API_ERROR',
                responseDescription: error.response?.data?.output_ResponseDesc || error.message
            };
        }
    }

    // ─────────────────────────────────────────────
    // QUERY TRANSACTION STATUS
    // ─────────────────────────────────────────────

    async queryTransactionStatus(transactionID, thirdPartyReference) {
        if (this.simulationMode) {
            return {
                success:             true,
                transactionStatus:   'Completed',
                responseCode:        'INS-0',
                responseDescription: '[SIMULATION] Transaction completed successfully'
            };
        }

        try {
            console.log(`🔍 Querying transaction status: ${transactionID}`);

            const sessionToken = await this.getSessionToken();

            const payload = {
                input_ServiceProviderCode: this.serviceProviderCode,
                input_ThirdPartyReference: thirdPartyReference,
                input_QueryReference:      transactionID
            };

            const response = await axios.post(
                `${this.baseUrl}${this.apiPath}/queryTransactionStatus/`,
                payload,
                {
                    headers: {
                        Authorization: `Bearer ${sessionToken}`,
                        'Content-Type': 'application/json'
                    }
                }
            );

            return {
                success:             true,
                transactionStatus:   response.data?.output_ResponseDesc || 'Unknown',
                responseCode:        response.data?.output_ResponseCode  || 'UNKNOWN',
                responseDescription: response.data?.output_ResponseDesc  || 'Status retrieved'
            };

        } catch (error) {
            console.error('❌ Status query error:', error.response?.data || error.message);
            return {
                success:             false,
                responseCode:        'API_ERROR',
                responseDescription: error.message
            };
        }
    }

    // ─────────────────────────────────────────────
    // TEST CONNECTION
    // ─────────────────────────────────────────────

    async testConnection() {
        try {
            const token = await this.getSessionToken();
            return {
                success:      true,
                message:      this.simulationMode ? 'Simulation mode active' : 'Connected to Vodacom DRC sandbox',
                environment:  this.environment,
                simulation:   this.simulationMode,
                sessionToken: token ? 'Valid' : 'Invalid'
            };
        } catch (error) {
            return {
                success:     false,
                message:     'Connection failed',
                environment: this.environment,
                simulation:  this.simulationMode,
                error:       error.message
            };
        }
    }

    // ─────────────────────────────────────────────
    // SIMULATION HELPERS  (MPESA_SIMULATION=true)
    // ─────────────────────────────────────────────

    _simulateC2B(phoneNumber, amount, currency, transactionRef) {
        const msisdn = this._normalisePhone(phoneNumber);
        const txID   = this._generateSimRef('C2B');

        console.log(`🧪 [SIMULATION] C2B deposit: ${amount} ${currency} from ${msisdn} | ref: ${transactionRef}`);

        return {
            success:             true,
            transactionID:       txID,
            conversationID:      this._generateSimRef('CONV'),
            thirdPartyReference: transactionRef,
            responseDescription: '[SIMULATION] C2B payment initiated – awaiting callback',
            simulated:           true
        };
    }

    _simulateB2C(phoneNumber, amount, currency, transactionRef) {
        const msisdn = this._normalisePhone(phoneNumber);
        const txID   = this._generateSimRef('B2C');

        console.log(`🧪 [SIMULATION] B2C payment: ${amount} ${currency} to ${msisdn} | ref: ${transactionRef}`);

        return {
            success:             true,
            transactionID:       txID,
            conversationID:      this._generateSimRef('CONV'),
            thirdPartyReference: transactionRef,
            responseDescription: '[SIMULATION] B2C payment sent successfully',
            simulated:           true
        };
    }

    // ─────────────────────────────────────────────
    // CONFIG VALIDATION
    // ─────────────────────────────────────────────

    validateConfig() {
        if (this.simulationMode) return true; // No keys needed in simulation

        const required = [
            'VODACOM_MPESA_API_KEY',
            'VODACOM_MPESA_PUBLIC_KEY',
            'VODACOM_MPESA_SERVICE_PROVIDER_CODE'
        ];

        const missing = required.filter(k => !process.env[k]);
        if (missing.length > 0) {
            throw new Error(`Missing environment variables: ${missing.join(', ')}`);
        }

        return true;
    }
}

module.exports = VodacomMpesaService;